version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gamedb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  game-service:
    build: .
    container_name: game-service
    depends_on:
      - mysql
    ports:
      - "8001:8001"
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: gamedb

volumes:
  mysql_data:
