version: "3.9"

services:
  clickhouse:
    image: clickhouse/clickhouse-server
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: root
    volumes:
      - clickhouse_data:/var/lib/clickhouse

  analytics-service:
    build: .
    container_name: analytics-service
    depends_on:
      - clickhouse
    ports:
      - "8003:8003"
    environment:
      CLICKHOUSE_HOST: clickhouse

volumes:
  clickhouse_data:

