version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: order-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orderdb
    ports:
      - "3309:3306"
    volumes:
      - order_mysql_data:/var/lib/mysql

  order-service:
    build: .
    container_name: order-service
    depends_on:
      - mysql
    ports:
      - "8002:8002"
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: orderdb

volumes:
  order_mysql_data:
